### ISSUE TITLE
Error IndexError: boolean index did not match indexed array along dimension 0; dimension is 780 but corresponding boolean dimension is 799

### ISSUE THREAD

**Issue by amitkayal** [zllrunning/face-makeup.PyTorch#7]
Hi,

Getting the following error. Is this due to size mismatch?

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
100% 44.7M/44.7M [00:00<00:00, 307MB/s]
Traceback (most recent call last):
  File "makeup.py", line 86, in <module>
    image = hair(image, parsing, part, color)
  File "makeup.py", line 54, in hair
    changed[parsing != part] = image[parsing != part]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 780 but corresponding boolean dimension is 799

**Comment by amitkayal** [comment]
Here is the input file
![girl-no-makeup](https://user-images.githubusercontent.com/10626280/98581696-df0ea200-22e7-11eb-86ae-215344172719.jpg)

**Comment by yaroslavmavliutov** [comment]
Hi @amitkayal 

You can add `np.repeat(parsing[:, :, np.newaxis], 3, axis=2)` to hair function. It works

**Comment by qihuijia** [comment]
> Hi @amitkayal
> 
> You can add `np.repeat(parsing[:, :, np.newaxis], 3, axis=2)` to hair function. It works

hi, where should I add this code?
